name: klinik
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.4+2

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  date_time_picker: ^2.1.0
  intl: ^0.17.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  carousel_slider: ^4.0.0
  path_provider: ^2.0.8
  youtube_player_flutter: ^8.0.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  package_info: ^2.0.2
  flutter_launcher_icons: ^0.9.2
  syncfusion_flutter_charts: ^19.4.48+1
  localstorage: ^4.0.0+1
  firebase_auth_web: ^3.3.7
  jiffy: ^5.0.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - .env
  #   - images/a_dot_ham.jpeg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"